fName = input("Enter your first name: ")
lName = input("Enter your last name: ")
mName = input("Enter your middle name: ") 
bDay = input("Enter your birthday [MM/DD/YYYY]: ")
Gender = input("Enter your gender [M/F]: ") 
Address = input("Enter your address: ") 
Course = input("Enter your course: ")
yearLevel = int(input ("Enter your year level: "))

print("Name: ", fName, "" , mName, "", lName )
print("Birthday: ", bDay)
print("Gender: ", Gender)
print("Address: ", Address)
print("Course: ", Course)
print("Year level: ", yearLevel )